<?php
// KENDİNİZE GÖRE DÜZENLEMELERİ YAPINIZ

DEFINE("SITE_URL", "");
DEFINE("DEFAULT_INDEX", "merhaba.php");
DEFINE("ERROR_PAGE", "_hata.php");

DEFINE("DB_HOST", "");
DEFINE("DB_USER", "");
DEFINE("DB_PASS", "");
DEFINE("DB_NAME", "");
DEFINE("DB_PERFIX", "");

DEFINE("SMTP_HOST", "");
DEFINE("SMTP_USERNAME", "");
DEFINE("SMTP_PASSWORD", "");
DEFINE("SMTP_SENDER", "");

DEFINE("DEFAULT_LANGUAGE", "tr");
DEFINE("SHOW_PHP_ERRORS", 1);
DEFINE("SESSION_START", FALSE);

// DEĞİŞİKLİK YAPILMASI ÖNERİLMİYOR

DEFINE("VIEW_FOLDER", "wmv_view/");
DEFINE("DIST_FOLDER", "wmv_dist/");
DEFINE("UPLOAD_FOLDER", "wmv_upload/");

?>